version: '3.8'
services:
  site-dev:
    build:
      context: .
      target: builder
    ports:
      - '4000:4000'
    volumes:
      - ./:/app

  site-prod:
    build:
      context: .
      target: final
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_BASE_DOMAIN_URL: https://dersu.uz
      NEXT_PUBLIC_ENABLE_PLAUSIBLE: true

